In [ ]:
import random

salary_list = [random.randint(50000, 100000) for _ in range(1_000_000)]

In [ ]:
import statistics

In [ ]:
%%timeit

statistics.mean(salary_list)

438 ms ± 112 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [ ]:
import numpy as np

In [ ]:
%%timeit
np.mean(salary_list)

85.9 ms ± 17.9 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [ ]:
my_array = np.array([1,2,3,4])

In [ ]:
my_array.mean()

np.float64(2.5)

In [ ]:
import numpy as np

In [ ]:
# job Title
job_titles = np.array(['Data Analyst', 'Data Scientist', 'Data Engineer', 'Machine Learning Engineer', 'AI Engineer'])

# Base salaries
base_salaries = np.array([60000, 80000, 75000, 90000, np.nan])

# Bonus rates
bonus_rates = np.array([.05, .1, .08, 0.12, np.nan])

In [ ]:
total_salaries = base_salaries * (1 + bonus_rates)
total_salaries

array([ 63000.,  88000.,  81000., 100800.,     nan])

In [ ]:
np.nanmean(total_salaries)

np.float64(83200.0)

# Problems

In [ ]:
import numpy as np

In [ ]:
application = np.array([10, 15, 7, 20, 25, 30, 5])

print(application)

[10 15  7 20 25 30  5]


In [ ]:
postings_list = [10, 15, 7, 20, 25, 30, 5]

postings = np.array(postings_list[:3])

print(postings)

[10 15  7]


In [ ]:
salaries_list = [70000, 85000, 60000, 95000, 80000]
salaries = np.array(salaries_list)
max_salary = np.max(salaries)
min_salary = np.min(salaries)

print(f"Maxmum salary is: {max_salary}")
print(f"Minimum salary is: {min_salary}")


Maxmum salary is: 95000
Minimum salary is: 60000
